### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by diegoaguayo** [raviteja83/SimpleDashboard#29]
Hello Ravi! 
I really liked your app. I'm currently working on a project to create a dashboard, so I would like to use your project as a starting point. If possible, could you please add a License to your repo?

[Here's a guide](https://opensource.guide/) on how you can make it. 

Thanks in advanced,
Diego

**Comment by raviteja83** [comment]
https://github.com/raviteja83/SimpleDashboard/commit/ce207fd61fdecf069f3b3261a35aa22e4f0ddb68
